# Dependencies
markdown: rdiscount

# Permalinks
permalink: pretty

# Url
baseurl: "http://reardestani.github.io/bootstrapee"

# Pagination
paginate: 10
paginate_path: "blog/page:num"

# Bloginfo
name: "Bootstrapee"
description: "Free, Sleek, High Quality, and Developer Friendly Web Resources"
version: "0.0.1"

# Custom variables
jquery_url: "https://code.jquery.com/jquery-1.10.2.min.js"
bootstrap_css_url: "//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css"
bootstrap_js_url: "//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"