# Dependencies
markdown: rdiscount

# Permalinks
permalink: /:title

# Url
baseurl: "http://reardestani.github.io/bootstrapee/"

# Pagination
# paginate: 3
# paginate_path: "/:num"

# Future
future: true

# Bloginfo
name: "Bootstrapee"
description: "Free, Sleek, High Quality, and Developer Friendly Web Resources"
version: "1.0.1"

# Notification
notification: 1

# Freebies
freebies: 7

# Gumroad download center link
gumroad-link: "https://gumroad.com/l/freebies"

# Custom variables
jquery_url: "https://code.jquery.com/jquery-1.9.0.min.js"
bootstrap_css_url: "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"
bootstrap_js_url: "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"
